# Generated by Django 3.1.6 on 2021-02-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Polldata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option1_count', models.IntegerField(max_length=1000)),
                ('option2_count', models.IntegerField(max_length=1000)),
                ('option3_count', models.IntegerField(max_length=1000)),
            ],
        ),
    ]
